"""Pydantic models for inference events.

Shared between the SDK (producer) and the ingestion-api (consumer) so both ends
agree on the wire format. The ingestion service imports these models too.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class EventStatus(str, Enum):
    SUCCESS = "success"
    ERROR = "error"
    CANCELLED = "cancelled"


class InferenceEvent(BaseModel):
    """One LLM call. Generated by the SDK, shipped to the ingestion endpoint."""

    request_id: UUID = Field(default_factory=uuid4)
    conversation_id: UUID | None = None
    message_id: UUID | None = None

    provider: str
    model: str

    status: EventStatus = EventStatus.SUCCESS
    error_code: str | None = None
    error_message: str | None = None

    started_at: datetime
    ended_at: datetime
    ttfb_ms: int | None = None

    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = None

    input_preview: str | None = None
    output_preview: str | None = None

    metadata: dict[str, Any] = Field(default_factory=dict)


class IngestRequest(BaseModel):
    """Wire envelope: a batch of events posted to /v1/logs."""

    events: list[InferenceEvent]


class IngestResponse(BaseModel):
    accepted: int
    rejected: int = 0
